spring.application.name=shieldgate-security-api
server.port=8081
spring.datasource.url=jdbc:h2:mem:shieldgatedb
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=

spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.jpa.hibernate.ddl-auto=update

spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

jwt.secret=this-is-a-very-long-secret-key-for-shieldgate-jwt-signing-1234567890
jwt.expiration=3600000